name: 转存到阿里Docker

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: '请填写docker-hub的仓库名'
        required: true
        default: 'xiaoyaliu/alist:latest'
  
env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
  IMAGE_NAME: "${{ github.event.inputs.image_name }}"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
         registry: $ALIYUN_REGISTRY
         username: $ALIYUN_REGISTRY_USER
         password: $ALIYUN_REGISTRY_PASSWORD
         
    - name: Build and push image Aliyun
      run: |
          docker pull $IMAGE_NAME
          if [[ $IMAGE_NAME == *"/"* ]]; then
             IMAGE_NAME="${IMAGE_NAME#*/}" 
          fi
          if [[ $IMAGE_NAME != *":"* ]]; then
             IMAGE_NAME="${IMAGE_NAME}:latest" 
          fi
          new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$IMAGE_NAME"
          echo "docker tag $IMAGE_NAME"
          docker tag $IMAGE_NAME $new_image
          echo "docker push $new_image"
          docker push $new_image
