name: 编译android二进制n2n

on:
   workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: 下载gcc
        uses: lmq8267/dl-musl@main
        with:
          target: arm-linux-musleabi
          static: true
          gccpath: /tmp
         
      - name: 构建openssl
        run: | 
         #编译安卓的openssl依赖1.1.1w版本
         git clone --recurse-submodules https://github.com/openssl/openssl /opt/openssl
         cd /opt/openssl
         sudo apt-get install libncurses5-dev
         
         
         ./Configure no-shared no-zlib linux-armv4 LDFLAGS="$LDFLAGS" CFLAGS="$CFLAGS"
         make -j$(nproc)
         make install INSTALLTOP=/opt/OpenSSL OPENSSLDIR=/opt/OpenSSL/ssl
         
      - name: 编译n2n
        run: |  
         git clone -b 3.0-stable https://github.com/cn1095/n2nn /opt/n2n
         mkdir -p /opt/n2n/build
         cd /opt/n2n/build
         
         #添加未生效的MAX MIN定义
         sed -i '/#ifndef _N2N_H_/i #define MAX(a,b) (a > b ? a : b)' /opt/n2n/include/n2n.h
         sed -i '/#ifndef _N2N_H_/i #define MIN(a,b) (a < b ? a : b)' /opt/n2n/include/n2n.h

         #修改安卓手机的tun模块位置
         sed -i 's|/dev/net/tun|/dev/tun|g' /opt/n2n/src/tuntap_linux.c
         
         #设置openssl为静态库，安卓无法用本机ssl库，添加一些库以及为安卓5.0版本以上添加-fPIE -pie选项
         sed -i 's|-Wall|-lm -lc -lz -landroid -static -lstdc++ -fPIE -pie -I/opt/OpenSSL/include -L/opt/OpenSSL/lib -Wl,-Bstatic -lssl -lcrypto -Wl,-Bdynamic -Wall|g' /opt/n2n/CMakeLists.txt
         sudo apt-get install libncurses5
         
         cmake ..
         make
         
         #查看文件属性以及依赖的库
         file edge
         readelf -d edge
         du -k edge
         #打包n2n所有程序
         #zip n2n-Android.zip edge example_edge_embed example_edge_embed_quick_edge_init example_sn_embed supernode n2n-benchmark
         mkdir /opt/n2n/build2
         mv edge /opt/n2n/build2/edge
         mv supernode /opt/n2n/build2/supernode
         mv example_edge_embed /opt/n2n/build2/example_edge_embed
         mv example_edge_embed_quick_edge_init /opt/n2n/build2/example_edge_embed_quick_edge_init
         mv example_sn_embed /opt/n2n/build2/example_sn_embed
         mv n2n-benchmark /opt/n2n/build2/n2n-benchmark

      - name : 上传
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: android_n2n_v2
         path: /opt/n2n/build2/*
