name: Rust-static-build
on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: lbl8603/vnts
        ref: master #默认使用master分支
    - name: 下载gcc
      uses: lmq8267/dl-musl@main
      with:
        toolchain: stable
        target: aarch64-linux-musl

    - name: test
      run: $CC -v

    - uses: actions/upload-artifact@v4
      with:
        name: vnts
        path: target/mipsel-unknown-linux-musl/release/vnts
