name: Rust-static-build
on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: lbl8603/vnts
        ref: master #默认使用master分支
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: mipsel-unknown-linux-uclibc
        override: true

    - name: Install cross
      run: cargo install cross

    - name: Cross build
      run: cross build --release --target mipsel-unknown-linux-uclibc --features normal,web
    - uses: actions/upload-artifact@v4
      with:
        name: vnts
        path: target/mipsel-unknown-linux-uclibc/release/vnts
