name: 打包docker

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["A编译candy"]
    types:
      - completed

jobs:
 check:
  runs-on: ubuntu-latest
  env:
      GITHUB_TOKEN: ${{ secrets.c8 }}
  outputs:
      RUN_ID: ${{ steps.getid.outputs.RUN_ID }}
  steps:
  - name: 获取id
    id: getid
    run: |
         #查找test仓库 流程名字为A编译candy的 最后一次流程id值
          RUN_ID=$(gh run list \
            --repo "${{ github.repository_owner }}/test" \
            --workflow "A编译candy" \
            --json "status,conclusion,updatedAt,databaseId" \
            --jq '[ .[] | select(.status=="completed") | select(.conclusion=="success") ] | max_by(.updatedAt) | .databaseId')

          if [[ -z "${RUN_ID}" ]]; then
            echo "无法获取到流程id"
            false
          fi
          echo "获取到${{ github.repository_owner }}流程id=${RUN_ID}"
          echo "RUN_ID=${RUN_ID}" >> $GITHUB_OUTPUT
 build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: 下载x86
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.c8 }}
          name: candy-x86_64-linux-musl
          path: /opt/bin/candy-x86
          run-id: ${{ needs.check.outputs.RUN_ID }}
          
      - name: 下载arm64
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.c8 }}
          name: candy-aarch64-linux-musl
          path: /opt/bin/candy-arm64
          run-id: ${{ needs.check.outputs.RUN_ID }}

      - name: 打包docker
        run: |
          file /opt/bin/candy-x86/candy
          file /opt/bin/candy-arm64/candy
          #执行后续打包docker操作


