name: 打包docker

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["A编译candy"]
    types:
      - completed

jobs:
 check:
  runs-on: ubuntu-latest
  env:
      GITHUB_TOKEN: ${{ secrets.c8 }}
  outputs:
      RUN_ID: ${{ steps.getid.outputs.RUN_ID }}
  steps:
  - name: 获取id
    id: getid
    run: |
          RUN_ID=$(gh run list \
            --repo "${{ github.repository_owner }}/test" \
            --workflow "A编译candy" \
            --json "status,conclusion,updatedAt,databaseId" \
            --jq '[ .[] | select(.status=="completed") | select(.conclusion=="success") ] | max_by(.updatedAt) | .databaseId')

          if [[ -z "${RUN_ID}" ]]; then
            echo "无法获取到流程id"
            false
          fi
          echo "获取到${{ github.repository_owner }}流程id=${RUN_ID}"
          echo "RUN_ID=${RUN_ID}" >> $GITHUB_OUTPUT
 build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: lanthora/candy
          ref: ${{ env.BRANCH }} #默认使用master分支
          
      - name: Print RUN_ID for debugging
        run: |
         echo "RUN_ID: ${RUN_ID}"
        
      - name: Download amd64 binaries
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.c8 }}
          name: candy-x86_64-linux-musl
          path: candy-x86_64-linux-musl
          run-id: ${RUN_ID}

      - name: 查找
        run: |
          find /opt -name "candy*"


