name: 编译frebsd-caddy

on:
  workflow_dispatch:
jobs:
 build: 
    runs-on: ubuntu-latest
    steps:
      - name: 获取最新Go
        run: |
          latest_version=$(curl -L -k -s https://golang.org/dl/?mode=json | grep -m 1 -o '"version": "[^"]*' | sed 's/"version": "//' | tr -d 'go" ')
          echo "go版本=$latest_version"
          echo "gotag=$latest_version" >> $GITHUB_ENV
      - name: 安装go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.gotag }}
      - 
        name: 编译
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          
          echo "开始构建"
          mkdir -p /opt/caddy
          cd /opt/caddy
          sudo timedatectl set-timezone "Asia/Shanghai"
          
          GOOS=freebsd GOARCH=amd64 xcaddy build \
          --with github.com/mholt/caddy-webdav \
          --with github.com/aksdb/caddy-cgi/v2 
          file caddy
          du -k caddy
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: caddy-FreeBSD
          path: /opt/caddy/caddy
