name: easytier-FreeBSD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '请填写构建EasyTier的EasyTier/EasyTier分支或提交记录，默认主分支main'
        required: true
        default: 'main'
  
env:
  CARGO_TERM_COLOR: always
  BRANCH: "${{ github.event.inputs.tag }}"
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: cn1095/EasyTier
          ref: ${{ env.BRANCH }} #默认使用main分支
      - name: Set up FreeBSD
        uses: cross-platform-actions/action@v0.23.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '13.2'
          shell: bash
          memory: 5G
          cpu_count: 4
          run: |
              sudo pkg install -y git protobuf
              git clone https://github.com/cn1095/boringtun ./boringtun
              mkdir -p ./easytier/libs
              cp -rf ./boringtun/boringtun ./easytier/libs/boringtun-easytier
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
              source $HOME/.cargo/env
              rustup set auto-self-update disable
              rustup install 1.77
              rustup default 1.77
              export CC=clang
              export CXX=clang++
              export CARGO_TERM_COLOR=always
              export RUSTFLAGS="-C opt-level=z -C target-cpu=native -C link-arg=-s"
              cargo build --release --no-default-features --features=bsd,websocket
              file ./target/release/easytier-core 
              mkdir -p ./target/release/et
              cp -rf ./target/release/easytier-core ./target/release/et/easytier-core 
              cp -rf ./target/release/easytier-cli ./target/release/et/easytier-cli
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: easytier-FreeBSD
          path: ./target/release/et/*
