name: candy-FreeBSD测试

on:
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: lanthora/candy
          ref: master #默认使用master分支
      - name: Set up FreeBSD
        uses: cross-platform-actions/action@v0.23.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '13.2'
          shell: bash
          memory: 5G
          cpu_count: 4
          run: |
              export CC=clang
              export CXX=clang++
              cmake -DCANDY_STATIC=1 -DTARGET_OPENSSL=BSD-generic64 -DCMAKE_BUILD_TYPE=Release .
              make -j$(nproc)
              file ./src/main/candy

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: candy-FreeBSD
          path: ./src/main/candy
