name: netlink-FreeBSD测试

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '请填写构建netlink的rustp2p/NetLink分支或提交记录，默认主分支main'
        required: true
        default: 'main'
  
env:
  CARGO_TERM_COLOR: always
  BRANCH: "${{ github.event.inputs.tag }}"
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: rustp2p/NetLink
          ref: ${{ env.BRANCH }} #默认使用main分支
          submodules: 'recursive'
      - name: Build 
        run: |
          git submodule update --remote
          cd web-app
          npm install
          npm run build
          cd ..
          mkdir -p ./static
          cp -r ./web-app/dist/* ./static/
          sudo apt-get update
          sudo apt-get install -y qemu qemu-user-static binfmt-support build-essential
          cargo install cross --git https://github.com/cross-rs/cross
          cross build --target x86_64-unknown-freebsd --release --features default
          mv ./target/release/net_link ./target/release/netlink
              
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: netlink_FreeBSD
          path: target/release/netlink
