name: Compile iperf3 using Cygwin on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: cmake gcc-g++ autoconf automake openssl-devel libtool git make

    - name: Create working directory
      run: mkdir -p /cygdrive/c/tmp

    - name: Clone iperf3 repository
      run: git clone https://github.com/esnet/iperf /cygdrive/c/tmp/iperf3

    - name: Build iperf3
      working-directory: /cygdrive/c/tmp/iperf3
      run: |
        ./bootstrap.sh
        ./configure --enable-static
        make

    - name: Package dependencies
      working-directory: /cygdrive/c/tmp/iperf3
      run: |
        mkdir -p /cygdrive/c/tmp/iperf3-package
        cp src/iperf3.exe /cygdrive/c/tmp/iperf3-package/
        cygcheck -v /cygdrive/c/tmp/iperf3/src/iperf3.exe > /cygdrive/c/tmp/iperf3-package/dependencies.txt
        for dll in $(cygcheck -v /cygdrive/c/tmp/iperf3/src/iperf3.exe | grep cyg | awk '{print $NF}'); do
          cp $dll /cygdrive/c/tmp/iperf3-package/
        done

    - name: Create archive
      run: |
        cd /cygdrive/c/tmp/iperf3-package
        tar -czvf iperf3-package.tar.gz *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: iperf3-package
        path: /cygdrive/c/tmp/iperf3-package/iperf3-package.tar.gz
