name: Compile iperf3 using Cygwin on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository:  esnet/iperf
        ref: 3.17.1

    - name: Set up Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
       packages: cmake gcc-g++ autoconf automake openssl-devel libtool

    - name: Compile iperf3
      run: |
        ./configure --enable-static-bin CFLAGS="-static -pthread"
        make
        make check

    - name: Gather DLLs
      run: |
        mkdir -p output
        cp src/iperf3.exe output/
        cygcheck output/iperf3.exe | grep -oP 'C:.+?\.dll' | xargs -I '{}' cp '{}' output/

    - name: Create Tarball of Binaries and DLLs
      run: |
        tar -czvf iperf3-windows-static.tar.gz -C output .

    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: iperf3-windows-static
        path: iperf3-windows-static.tar.gz
