name: A编译n2n-FreeBSD

on:
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ntop/n2n
          ref: dev #默认使用dev分支
      - name: Set up FreeBSD
        uses: cross-platform-actions/action@v0.15.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '13.2'
          shell: bash
          memory: 5G
          cpu_count: 4
          run: |
            sudo pkg install -y \
              autoconf \
              automake \
              gcc \
              git \
              gmake \
              python3 \
              pkgconf
            ./autogen.sh
            ./configure
            gmake all
            file supernode

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
           name: n2n-freebsd
           path: n2n/build/
