name: A编译n2n-FreeBSD

on:
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ntop/n2n
          ref: 3.0-stable #默认使用dev分支
      - name: Set up FreeBSD
        uses: cross-platform-actions/action@v0.15.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '13.2'
          shell: bash
          memory: 5G
          cpu_count: 4
          run: |
            sudo pkg install -y \
              autoconf \
              automake \
              git-tiny \
              gmake \
              python3 \
              jq \
              bash \
              pkgconf
            ./autogen.sh
            ./configure CC=clang LDFLAGS="-static" CFLAGS="-static" 
            gmake all
            file supernode
            mkdir -p ./bin
            mv -f edge ./bin/edge
            mv -f supernode ./bin/supernode
            mv -f example_edge_embed_quick_edge_init ./bin/example_edge_embed_quick_edge_init
            mv -f example_edge_embed ./bin/example_edge_embed
            mv -f example_sn_embed ./bin/example_sn_embed
            mv -f n2n-benchmark ./bin/n2n-benchmark

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
           name: n2n-freebsd
           path: ./bin/*
