name: 编译cloudflared

on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 获取最新Go
        run: |
          latest_version=$(curl -L -k -s https://golang.org/dl/?mode=json | grep -m 1 -o '"version": "[^"]*' | sed 's/"version": "//' | tr -d 'go" ')
          echo "go版本=$latest_version"
          echo "gotag=$latest_version" >> $GITHUB_ENV
      - name: 安装go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.gotag }}
      - 
        name: 编译
        run: |
          git clone https://github.com/cloudflare/cloudflared ../src
          sudo timedatectl set-timezone "Asia/Shanghai"
          cd ../src
          sed -i "s|-ldflags='|-ldflags=' -s -w |g" ./Makefile
          GOOS=freebsd GOARCH=amd64 make cloudflared
          file cloudflared
          mv -f cloudflared /opt/cloudflared
      - name: 上传
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cloudflared
          path: /opt/cloudflared
