name: AABuild staticx for MIPS

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: JonathonReinhart/staticx
          ref: main
          
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential musl-tools musl-dev 

      - name: Install Python and dependencies
        run: |
          sudo apt-get install -y python3 python3-pip
          pip3 install meson
          
      - name: 下载gcc
        uses: lmq8267/dl-musl@main
        with:
          target: mipsel-linux-muslsf
          static: true
          
      - name: Build libarchive
        run: |
          wget https://www.libarchive.org/downloads/libarchive-3.6.1.tar.gz
          tar -xzf libarchive-3.6.1.tar.gz
          cd libarchive-3.6.1
          CC=mipsel-linux-muslsf-gcc ./configure --host=mipsel-linux-muslsf --enable-static --disable-shared
          make
          sudo make install

      - name: Clone and build staticx
        run: |
          git clone https://github.com/JonathonReinhart/staticx.git
          cd staticx
          CC=mipsel-linux-muslsf-gcc CXX=mipsel-linux-muslsf-g++ python3 setup.py build_ext --static

      - name: Package staticx
        run: |
          pip3 install pyinstaller
          pyinstaller --onefile --static staticx.py
          echo "查看信息"
          file dist/staticx
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: staticx-mipsel
          path: dist/staticx
