name: 测试编译easytier

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '请填写构建easytier的EasyTier/EasyTier分支或版本号，默认主分支main'
        required: true
        default: 'main'
      upx:
        description: '使用upx压缩二进制程序以最大化减少体积'
        required: true
        default: true
        type: boolean

env:
  BRANCHES: "${{ github.event.inputs.tag }}"
  CARGO_TERM_COLOR: always
  TZ: Asia/Shanghai
  
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 下载编译工具
        run: |
          mkdir -p /opt/musl_gcc
          rustup set auto-self-update disable
          rustup install 1.75
          rustup default 1.75
          
          wget -q -c https://more.musl.cc/x86_64-linux-musl/armv5l-linux-musleabi-cross.tgz -P /opt/musl_gcc/
          tar zxf /opt/musl_gcc/armv5l-linux-musleabi-cross.tgz -C /opt/musl_gcc/
          sudo ln -s /opt/musl_gcc/armv5l-linux-musleab-cross/bin/*gcc /usr/bin/
          #sudo apt-get update && sudo apt-get install -qq crossbuild-essential-arm64 crossbuild-essential-armhf musl-tools protobuf-compiler
          
          rustup target add armv5te-unknown-linux-musleabi

          #添加交叉编译配置
          cat >>~/.cargo/config <<EOF
          [target.armv5te-unknown-linux-musleabi]
          linker = "armv5l-linux-musleabi-gcc"
          rustflags = ["-C", "target-feature=+crt-static",
          "-L", "/opt/musl_gcc/armv5l-linux-musleabi-cross/armv5l-linux-musleabi/lib",
          "-L", "/opt/musl_gcc/armv5l-linux-musleabi-cross/lib/gcc/armv5l-linux-musleabi/11.2.1",
          "-l", "atomic"]  
          EOF
      - name: 安装 UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true
      - name: 编译
        run: |
          tagg=${{ env.BRANCHES }}
          [[ -z $tagg ]] && tagg=main
          git clone -b ${{ env.BRANCHES }} https://github.com/EasyTier/EasyTier /opt/et
          cd /opt/et
          mkdir -p /opt/bin
          
          cargo build --release --target armv5te-unknown-linux-musleabi
          
          /opt/musl_gcc/armv5te-unknown-linux-musleabi-cross/bin/armv5te-unknown-linux-musleabi-strip ./target/armv5te-unknown-linux-musleabi/release/easytier-core
          /opt/musl_gcc/armv5te-unknown-linux-musleabi-cross/bin/armv5te-unknown-linux-musleabi-strip ./target/armv5te-unknown-linux-musleabi/release/easytier-cli
         
      - name: 压缩
        if: github.event.inputs.upx != 'false'
        run: |
          upx --lzma --best /opt/et/target/armv5te-unknown-linux-musleabi/release/easytier-core
          upx --lzma --best /opt/et/target/armv5te-unknown-linux-musleabi/release/easytier-cli
      - name: 打包
        run: |
          cd /opt/et/target/armv5te-unknown-linux-musleabi/release
          file easytier-core
          #tar -czvf easytier-armv5te-unknown-linux-musleabi.tar.gz easytier-core easytier-cli
          cp -f ./easytier-core /opt/bin/easytier-core
          cp -f ./easytier-cli /opt/bin/easytier-cli
      - name: 上传
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: easytier-armv5te-unknown-linux-musleabi
          path: /opt/bin/*
      
