name: Build vntAPP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
       channel: stable  # 使用最新的 Flutter 版本

    - name: Build APK
      run: |
       echo "安装依赖"
       sudo apt-get install ninja-build cmake g++ libgtk-3-dev libayatana-appindicator3-dev
       echo "安装打包linuxdeploy"
       wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
       chmod +x linuxdeploy-x86_64.AppImage
       sudo mv linuxdeploy-x86_64.AppImage /usr/local/bin/linuxdeploy
       echo "安装打包AppImage"
       wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
       sudo apt-get install fuse libfuse2
       chmod +x appimagetool-x86_64.AppImage
       sudo mv appimagetool-x86_64.AppImage /usr/local/bin/appimagetool
       echo "下载源码"
       git clone -b flutter https://github.com/lbl8603/VntApp /opt/vnt
       cd /opt/vnt
       flutter pub outdated
       flutter config --enable-linux-desktop
       echo "开始构建"
       flutter build linux
       du -lah /opt/vnt/build/linux/x64/release/bundle/
       echo "打包AppImage"
       cat <<EOF > /opt/vnt/build/linux/x64/release/bundle/VntApp.desktop
       [Desktop Entry]
       Name=VntApp
       Exec=vnt_app
       Icon=app_icon
       Type=Application
       Categories=Utility;
       EOF
       linuxdeploy --appdir /opt/vnt/build/linux/x64/release/bundle/ --executable /opt/vnt/build/linux/x64/release/bundle/vnt_app
       cp /opt/vnt/build/linux/x64/release/bundle/data/flutter_assets/assets/app_icon.png /opt/vnt/build/linux/x64/release/bundle/app_icon.png
       appimagetool /opt/vnt/build/linux/x64/release/bundle/ /opt/vntAPP.AppImage
    
    - name: 上传
      uses: actions/upload-artifact@v4
      if: always()
      with:
          name: vntAPP-linux
          path: /opt/vntAPP.AppImage
       
