name: Build vntAPP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
       channel: stable  # 使用最新的 Flutter 版本

    - name: Build APK
      run: |
       sudo apt-get install ninja-build cmake g++ libgtk-3-dev
       git clone -b flutter https://github.com/lbl8603/VntApp /opt/vnt
       cd /opt/vnt
       flutter pub outdated
       flutter config --enable-linux-desktop
       flutter build linux
       du -lah /opt/vnt/build
