name: vnts-阿里docker测试

on:
  workflow_dispatch:
env:
  tag: "v1.2.9"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 下载二进制文件
        run: |
          mkdir -p /opt/vnt
          cd /opt/vnt
          wget -c https://github.com/lmq8267/vnts/releases/download/${{ env.tag }}/vnts_x86_64-unknown-linux-musl -P /opt/vnt/
          chmod a+x vnts_x86_64-unknown-linux-musl
          mv vnts_x86_64-unknown-linux-musl vnts_amd64

          wget -c https://github.com/lmq8267/vnts/releases/download/${{ env.tag }}/vnts_i686-unknown-linux-musl -P /opt/vnt/
          chmod a+x vnts_i686-unknown-linux-musl
          mv vnts_i686-unknown-linux-musl vnts_386

          wget -c https://github.com/lmq8267/vnts/releases/download/${{ env.tag }}/vnts_aarch64-unknown-linux-musl -P /opt/vnt/
          chmod a+x vnts_aarch64-unknown-linux-musl
          mv vnts_aarch64-unknown-linux-musl vnts_arm64
          
          wget -c https://github.com/lmq8267/vnts/releases/download/${{ env.tag }}/vnts_armv7-unknown-linux-musleabi -P /opt/vnt/
          chmod a+x vnts_armv7-unknown-linux-musleabi
          mv vnts_armv7-unknown-linux-musleabi vnts_armv7

          wget -c https://github.com/lmq8267/vnts/releases/download/${{ env.tag }}/vnts_arm-unknown-linux-musleabi -P /opt/vnt/
          chmod a+x vnts_arm-unknown-linux-musleabi
          mv vnts_arm-unknown-linux-musleabi vnts_armv5
          
      - name: Setup QEMU
        uses: dbhi/qus/action@main
      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 构建发布
        run: |
         git clone https://github.com/lmq8267/vnts /opt/src
         mv /opt/src/Dockerfile /opt/vnts/Dockerfile
         cd /opt/vnts
         echo $ALIYUN_REGISTRY_PASSWORD | docker login $ALIYUN_REGISTRY -u $ALIYUN_REGISTRY_USER --password-stdin 
         sudo docker buildx create --use
         sudo docker buildx build --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6 -t lmq8267/vntst:${{ needs.check.outputs.ver }} . --push
         sudo docker buildx build --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6 -t lmq8267/vntst . --push
         sudo rm -rf /home/runner/.docker/config.json
         sudo rm -rf /root/.docker/config.json
