name: 打包网页

on:
  workflow_dispatch:
    inputs:
      repo:
        description: '请输入源码仓库 【用户名/仓库名】'
        required: true
        default: ''
      branch:
        description: '请输入仓库的分支或版本号，默认main分支'
        required: true
        default: 'main'

env:
  branch: "${{ github.event.inputs.branch }}"
  repo: "${{ github.event.inputs.repo }}"
  TZ: Asia/Shanghai
  
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
         repository: ${{ github.event.inputs.repo }}
         ref: ${{ github.event.inputs.branch }}
         
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21' # 使用的 Node.js 版本，可调整
          
      - name: 安装pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
          
      - name: 构建 HTML
        run: |
          #pnpm -r install
          #pnpm -r build
          npm install
          npm run build
          ls -alh
      - name: 上传
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: html
          path: ./dist/*
